source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

#屏蔽警告
inhibit_all_warnings!

target "MallO2O" do

pod 'SDWebImage'			# SD图片库
pod 'SVProgressHUD'			# 提示信息库
pod 'IQKeyboardManager'		# 文本输入
pod 'RDVTabBarController'	# tabBar
pod 'MJRefresh'				# MJ刷新
pod 'MJExtension'			# MJ解析数据解析
pod 'PureLayout'			# 自动布局
pod 'AFNetworking'			# AFNetworking 网络库
pod 'Base64nl'				# Base64加密
pod 'Masonry'				# Masonry 自动布局框架
pod 'WebViewJavascriptBridge'		# webView 交互
pod 'UMengSocialCOM'        #友盟
pod 'RegexKitLite'          #正则表达式
pod 'Reachability'          #网络环境
pod 'SDCycleScrollView'     #轮播
end